name       : haskell-conduit
version    : 1.2.9
release    : 1
source     :
    - http://hackage.haskell.org/package/conduit-1.2.9/conduit-1.2.9.tar.gz : 8adf9d8916dcb7abf86c4c82cc1c92e99dea8d0a9a5835302a824142d214cf06
license    : MIT
component  : programming.haskell
summary    : conduit is a solution to the streaming data problem
description: |
    conduit is a solution to the streaming data problem, allowing for production, transformation, and consumption of streams of data in constant memory. It is an alternative to lazy I/O which guarantees deterministic resource handling.
builddeps  :
    - haskell-cabal-install
    - haskell-resourcet
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register