name       : haskell-conduit
version    : 1.3.0.2
release    : 2
source     :
    - https://hackage.haskell.org/package/conduit-1.3.0.2/conduit-1.3.0.2.tar.gz : c0f099d242504e65a78e1cbb54c18afad45fe2c9297d1d918ce28ae7dc4a1e5b
license    : MIT
component  : programming.haskell
summary    : conduit is a solution to the streaming data problem
description: |
    conduit is a solution to the streaming data problem, allowing for production, transformation, and consumption of streams of data in constant memory. It is an alternative to lazy I/O which guarantees deterministic resource handling.
builddeps  :
    - haskell-cabal-install
    - haskell-mono-traversable
    - haskell-resourcet
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |-
    %cabal_install
    %cabal_register
